import { formatCad, formatPct, stripEmoji } from '../../components/tools/format';
import {
  formatPctFr,
  getBanqueAvgForProfil,
  getIaPctForProfil,
  PROFIL_RISQUE_LABELS,
} from '../../data/comparateurRendementsRates';

const money = (v) => formatCad(v);
const pct = (v, d = 1) => formatPct(v, d);

/** Configs UI : fields + buildPresentation(calcResults, values) */
export const toolViews = {
  'budget-mensuel': {
    defaults: {
      salaire: '4500',
      revenus_sec: '0',
      allocations: '0',
      autres_rev: '0',
      loyer: '1400',
      electricite: '120',
      assur_hab: '40',
      taxes: '0',
      telecom: '90',
      auto_paiement: '350',
      essence: '200',
      assur_auto: '120',
      entretien_auto: '50',
      transport_commun: '0',
      epicerie: '600',
      restaurants: '150',
      vetements: '50',
      soins: '40',
      assur_vie: '40',
      assur_maladie: '0',
      medicaments: '20',
      dentiste: '0',
      carte_credit: '100',
      pret_etudiant: '0',
      marge: '0',
      pension: '0',
      reer: '200',
      celi: '100',
      reee: '0',
      urgence: '50',
      abonnements: '40',
      loisirs: '100',
      vacances: '100',
      cadeaux: '50',
    },
    fields: [
      { id: 'salaire', label: 'Salaire net mensuel ($)', type: 'number', section: 'Revenus' },
      { id: 'revenus_sec', label: 'Revenus secondaires ($)', type: 'number', section: 'Revenus' },
      { id: 'allocations', label: 'Allocations ($)', type: 'number', section: 'Revenus' },
      { id: 'autres_rev', label: 'Autres revenus ($)', type: 'number', section: 'Revenus' },
      { id: 'loyer', label: 'Loyer / hypothèque ($)', type: 'number', section: 'Logement' },
      { id: 'electricite', label: 'Électricité ($)', type: 'number', section: 'Logement' },
      { id: 'assur_hab', label: 'Assurance habitation ($)', type: 'number', section: 'Logement' },
      { id: 'taxes', label: 'Taxes ($)', type: 'number', section: 'Logement' },
      { id: 'telecom', label: 'Télécom ($)', type: 'number', section: 'Logement' },
      { id: 'auto_paiement', label: 'Paiement auto ($)', type: 'number', section: 'Transport' },
      { id: 'essence', label: 'Essence ($)', type: 'number', section: 'Transport' },
      { id: 'assur_auto', label: 'Assurance auto ($)', type: 'number', section: 'Transport' },
      { id: 'entretien_auto', label: 'Entretien auto ($)', type: 'number', section: 'Transport' },
      { id: 'transport_commun', label: 'Transport en commun ($)', type: 'number', section: 'Transport' },
      { id: 'epicerie', label: 'Épicerie ($)', type: 'number', section: 'Quotidien' },
      { id: 'restaurants', label: 'Restaurants ($)', type: 'number', section: 'Quotidien' },
      { id: 'vetements', label: 'Vêtements ($)', type: 'number', section: 'Quotidien' },
      { id: 'soins', label: 'Soins personnels ($)', type: 'number', section: 'Quotidien' },
      { id: 'assur_vie', label: 'Assurance vie ($)', type: 'number', section: 'Santé' },
      { id: 'assur_maladie', label: 'Assurance maladie ($)', type: 'number', section: 'Santé' },
      { id: 'medicaments', label: 'Médicaments ($)', type: 'number', section: 'Santé' },
      { id: 'dentiste', label: 'Dentiste ($)', type: 'number', section: 'Santé' },
      { id: 'carte_credit', label: 'Carte de crédit ($)', type: 'number', section: 'Dettes' },
      { id: 'pret_etudiant', label: 'Prêt étudiant ($)', type: 'number', section: 'Dettes' },
      { id: 'marge', label: 'Marge de crédit ($)', type: 'number', section: 'Dettes' },
      { id: 'pension', label: 'Pension alimentaire ($)', type: 'number', section: 'Dettes' },
      { id: 'reer', label: 'REER ($)', type: 'number', section: 'Épargne' },
      { id: 'celi', label: 'CELI ($)', type: 'number', section: 'Épargne' },
      { id: 'reee', label: 'REEE ($)', type: 'number', section: 'Épargne' },
      { id: 'urgence', label: 'Fonds d’urgence ($)', type: 'number', section: 'Épargne' },
      { id: 'abonnements', label: 'Abonnements ($)', type: 'number', section: 'Loisirs' },
      { id: 'loisirs', label: 'Loisirs ($)', type: 'number', section: 'Loisirs' },
      { id: 'vacances', label: 'Vacances ($)', type: 'number', section: 'Loisirs' },
      { id: 'cadeaux', label: 'Cadeaux ($)', type: 'number', section: 'Loisirs' },
    ],
    buildPresentation: (r) => ({
      rows: [
        { label: 'Revenus', value: money(r.res_revenus) },
        { label: 'Dépenses', value: money(r.res_depenses) },
        { label: 'Épargne', value: money(r.res_epargne) },
        { label: 'Solde disponible', value: money(r.res_solde), emphasize: true },
        { label: 'Taux d’épargne', value: pct(r.taux_epargne, 0) },
        { label: 'Ratio logement', value: pct(r.ratio_logement, 0) },
      ],
      chart: {
        type: 'stacked-line',
        title: 'Répartition mensuelle',
        data: (() => {
          const cats = [
            ['logement', r.total_logement || 0],
            ['transport', r.total_transport || 0],
            ['quotidien', r.total_quotidien || 0],
            ['sante', r.total_sante || 0],
            ['dettes', r.total_dettes || 0],
            ['loisirs', r.total_loisirs || 0],
            ['epargne', r.total_epargne || 0],
          ];
          const labels = {
            logement: 'Logement',
            transport: 'Transport',
            quotidien: 'Quotidien',
            sante: 'Santé',
            dettes: 'Dettes',
            loisirs: 'Loisirs',
            epargne: 'Épargne',
          };
          let running = {
            logement: 0,
            transport: 0,
            quotidien: 0,
            sante: 0,
            dettes: 0,
            loisirs: 0,
            epargne: 0,
          };
          return cats.map(([key, value]) => {
            running = { ...running, [key]: value };
            return { name: labels[key], ...running };
          });
        })(),
        series: [
          { dataKey: 'logement', name: 'Logement' },
          { dataKey: 'transport', name: 'Transport' },
          { dataKey: 'quotidien', name: 'Quotidien' },
          { dataKey: 'sante', name: 'Santé' },
          { dataKey: 'dettes', name: 'Dettes' },
          { dataKey: 'loisirs', name: 'Loisirs' },
          { dataKey: 'epargne', name: 'Épargne' },
        ],
      },
      note: stripEmoji(r.conseil),
    }),
  },

  'simulateur-reer': {
    defaults: {
      revenu: '75000',
      cotisation: '10000',
      situation: 'celibataire',
      enfants: '0',
    },
    fields: [
      { id: 'revenu', label: 'Revenu annuel brut ($)', type: 'number', section: 'Situation' },
      { id: 'cotisation', label: 'Cotisation REER ($)', type: 'number', section: 'Situation' },
      {
        id: 'situation',
        label: 'Situation familiale',
        type: 'select',
        section: 'Situation',
        options: [
          { value: 'celibataire', label: 'Célibataire' },
          { value: 'couple', label: 'En couple' },
          { value: 'monoparental', label: 'Monoparental' },
        ],
      },
      {
        id: 'enfants',
        label: 'Enfants à charge',
        type: 'select',
        section: 'Situation',
        options: [
          { value: '0', label: '0' },
          { value: '1', label: '1' },
          { value: '2', label: '2' },
          { value: '3', label: '3+' },
        ],
      },
    ],
    buildPresentation: (r) => ({
      rows: [
        { label: 'Cotisation', value: money(r.r_cotisation) },
        { label: 'Droits max estimés', value: money(r.droits_max) },
        { label: 'Taux marginal combiné', value: `${r.r_taux} %` },
        { label: 'Économie d’impôt', value: money(r.r_economie), emphasize: true },
        { label: 'Portion fédérale', value: money(r.r_federal) },
        { label: 'Portion Québec', value: money(r.r_quebec) },
        { label: `Projection ${r.annees_projection} ans (5 %)`, value: money(r.valeur_future) },
      ],
      chart: {
        type: 'stacked-line',
        title: 'Impact fiscal',
        stacked: false,
        data: [
          { name: 'Avant REER', impot: r.impot_avant || 0 },
          { name: 'Après REER', impot: r.impot_apres || 0 },
        ],
        series: [{ dataKey: 'impot', name: 'Impôt estimé' }],
      },
      note: stripEmoji(r.conseil),
    }),
  },

  'calculateur-assurance-vie-complet': {
    defaults: {
      hypotheque: '250000',
      pret_auto: '0',
      cartes: '5000',
      marge_credit: '0',
      autres_dettes: '0',
      revenu_net: '5000',
      pct_remplacer: '70',
      nb_annees: '15',
      revenu_conjoint: '0',
      etudes: '30000',
      nb_enfants: '2',
      urgence: '15000',
      funerailles: '15000',
      legs: '0',
      av_actuelle: '0',
      av_groupe: '50000',
      epargnes: '20000',
    },
    fields: [
      { id: 'hypotheque', label: 'Hypothèque ($)', type: 'number', section: 'Dettes' },
      { id: 'pret_auto', label: 'Prêt auto ($)', type: 'number', section: 'Dettes' },
      { id: 'cartes', label: 'Cartes de crédit ($)', type: 'number', section: 'Dettes' },
      { id: 'marge_credit', label: 'Marge de crédit ($)', type: 'number', section: 'Dettes' },
      { id: 'autres_dettes', label: 'Autres dettes ($)', type: 'number', section: 'Dettes' },
      { id: 'revenu_net', label: 'Revenu net mensuel ($)', type: 'number', section: 'Revenu' },
      { id: 'pct_remplacer', label: '% à remplacer', type: 'number', section: 'Revenu' },
      { id: 'nb_annees', label: 'Années de remplacement', type: 'number', section: 'Revenu' },
      { id: 'revenu_conjoint', label: 'Revenu net conjoint ($)', type: 'number', section: 'Revenu' },
      { id: 'nb_enfants', label: 'Nombre d’enfants', type: 'number', section: 'Éducation' },
      { id: 'etudes', label: 'Coût études / enfant ($)', type: 'number', section: 'Éducation' },
      { id: 'urgence', label: 'Fonds d’urgence ($)', type: 'number', section: 'Final' },
      { id: 'funerailles', label: 'Frais funéraires ($)', type: 'number', section: 'Final' },
      { id: 'legs', label: 'Legs désiré ($)', type: 'number', section: 'Final' },
      { id: 'av_actuelle', label: 'Assurance vie actuelle ($)', type: 'number', section: 'Actifs' },
      { id: 'av_groupe', label: 'Assurance collective ($)', type: 'number', section: 'Actifs' },
      { id: 'epargnes', label: 'Épargnes disponibles ($)', type: 'number', section: 'Actifs' },
    ],
    buildPresentation: (r) => ({
      rows: [
        { label: 'Dettes', value: money(r.r_dettes) },
        { label: 'Remplacement de revenu', value: money(r.r_revenu) },
        { label: 'Éducation', value: money(r.r_education) },
        { label: 'Frais finaux / legs', value: money(r.r_heritage) },
        { label: 'Actifs existants', value: money(r.r_actifs) },
        { label: 'Besoin net', value: money(r.r_total), emphasize: true },
        { label: 'Couverture suggérée', value: money(r.besoin_recommande) },
        { label: 'Type suggéré', value: r.type_assurance || '—' },
      ],
      chart: {
        type: 'stacked-line',
        title: 'Composition du besoin',
        data: [
          {
            name: 'Dettes',
            dettes: Math.max(0, r.r_dettes || 0),
            revenu: 0,
            education: 0,
            final: 0,
          },
          {
            name: 'Revenu',
            dettes: Math.max(0, r.r_dettes || 0),
            revenu: Math.max(0, r.r_revenu || 0),
            education: 0,
            final: 0,
          },
          {
            name: 'Éducation',
            dettes: Math.max(0, r.r_dettes || 0),
            revenu: Math.max(0, r.r_revenu || 0),
            education: Math.max(0, r.r_education || 0),
            final: 0,
          },
          {
            name: 'Final',
            dettes: Math.max(0, r.r_dettes || 0),
            revenu: Math.max(0, r.r_revenu || 0),
            education: Math.max(0, r.r_education || 0),
            final: Math.max(0, r.r_heritage || 0),
          },
        ],
        series: [
          { dataKey: 'dettes', name: 'Dettes' },
          { dataKey: 'revenu', name: 'Revenu' },
          { dataKey: 'education', name: 'Éducation' },
          { dataKey: 'final', name: 'Final' },
        ],
      },
      note: stripEmoji(r.conseil),
    }),
  },

  'simulateur-reee': {
    defaults: {
      cotisation: '2500',
      nb_enfants: '1',
      revenu: '80000',
      droits_inutilises: '0',
    },
    fields: [
      { id: 'cotisation', label: 'Cotisation annuelle totale ($)', type: 'number', section: 'REEE' },
      { id: 'nb_enfants', label: 'Nombre d’enfants', type: 'number', section: 'REEE', min: 1 },
      { id: 'revenu', label: 'Revenu familial net ($)', type: 'number', section: 'REEE' },
      {
        id: 'droits_inutilises',
        label: 'Droits de subvention inutilisés ($)',
        type: 'number',
        section: 'REEE',
      },
    ],
    buildPresentation: (r) => ({
      rows: [
        { label: 'SCEE', value: money(r.scee) },
        { label: 'IQEE', value: money(r.iqee) },
        { label: 'BEC', value: money(r.bec) },
        { label: 'Total subventions (année)', value: money(r.total_sub), emphasize: true },
        { label: 'Rendement des subventions', value: `${r.rendement_sub} %` },
        { label: 'Projection cotisations (18 ans)', value: money(r.proj_cotis) },
        { label: 'Projection subventions', value: money(r.proj_sub) },
        { label: 'Projection totale', value: money(r.proj_total), emphasize: true },
      ],
      chart: {
        type: 'stacked-line',
        title: 'Projection 18 ans',
        data: [
          { name: 'Départ', cotisations: 0, subventions: 0, rendement: 0 },
          {
            name: '18 ans',
            cotisations: r.proj_cotis || 0,
            subventions: r.proj_sub || 0,
            rendement: r.proj_rend || 0,
          },
        ],
        series: [
          { dataKey: 'cotisations', name: 'Cotisations' },
          { dataKey: 'subventions', name: 'Subventions' },
          { dataKey: 'rendement', name: 'Rendement' },
        ],
      },
      note: stripEmoji(r.conseil),
    }),
  },

  'fonds-urgence': {
    defaults: {
      logement: '1400',
      alimentation: '600',
      transport: '350',
      assurances: '200',
      dettes: '150',
      autres: '100',
      stabilite: 'stable',
      personnes: '2',
      secteur: 'prive',
      epargne_actuelle: '5000',
    },
    fields: [
      { id: 'logement', label: 'Logement ($)', type: 'number', section: 'Dépenses essentielles' },
      { id: 'alimentation', label: 'Alimentation ($)', type: 'number', section: 'Dépenses essentielles' },
      { id: 'transport', label: 'Transport ($)', type: 'number', section: 'Dépenses essentielles' },
      { id: 'assurances', label: 'Assurances ($)', type: 'number', section: 'Dépenses essentielles' },
      { id: 'dettes', label: 'Paiements de dettes ($)', type: 'number', section: 'Dépenses essentielles' },
      { id: 'autres', label: 'Autres essentiels ($)', type: 'number', section: 'Dépenses essentielles' },
      {
        id: 'stabilite',
        label: 'Stabilité d’emploi',
        type: 'select',
        section: 'Situation',
        options: [
          { value: 'stable', label: 'Stable' },
          { value: 'moyen', label: 'Moyenne' },
          { value: 'variable', label: 'Variable' },
          { value: 'precaire', label: 'Précaire' },
        ],
      },
      { id: 'personnes', label: 'Personnes à charge', type: 'number', section: 'Situation' },
      {
        id: 'secteur',
        label: 'Secteur',
        type: 'select',
        section: 'Situation',
        options: [
          { value: 'prive', label: 'Privé' },
          { value: 'public', label: 'Public' },
          { value: 'autonome', label: 'Travailleur autonome' },
          { value: 'contractuel', label: 'Contractuel' },
        ],
      },
      { id: 'epargne_actuelle', label: 'Épargne actuelle ($)', type: 'number', section: 'Situation' },
    ],
    buildPresentation: (r) => ({
      rows: [
        { label: 'Dépenses mensuelles', value: money(r.depenses_mois) },
        { label: 'Mois recommandés', value: r.mois_recommandes },
        { label: 'Objectif (fourchette)', value: r.montant_range },
        { label: 'Objectif moyen', value: money(r.objectif_moyen), emphasize: true },
        { label: 'Épargne actuelle', value: money(r.epargne_actuelle) },
        { label: 'Montant manquant', value: money(r.epargne_restant) },
        { label: 'Progression', value: `${r.epargne_pct} %` },
        { label: 'Épargne mensuelle suggérée', value: money(r.epargne_mensuelle) },
      ],
      chart: {
        type: 'stacked-line',
        title: 'Progression vers l’objectif',
        stacked: false,
        data: [
          {
            name: 'Aujourd’hui',
            actuel: r.epargne_actuelle || 0,
            objectif: r.objectif_moyen || 0,
          },
          {
            name: 'Cible',
            actuel: r.objectif_moyen || 0,
            objectif: r.objectif_moyen || 0,
          },
        ],
        series: [
          { dataKey: 'actuel', name: 'Épargne actuelle' },
          { dataKey: 'objectif', name: 'Objectif' },
        ],
      },
      note: stripEmoji(r.conseil),
    }),
  },

  'comparateur-reer-celi': {
    defaults: {
      revenu_actuel: '80000',
      montant: '10000',
      revenu_retraite: '50000',
      horizon: '20',
      rendement: '5',
      reinvestir: 'oui',
    },
    fields: [
      { id: 'revenu_actuel', label: 'Revenu actuel ($)', type: 'number', section: 'Paramètres' },
      { id: 'montant', label: 'Montant à investir ($)', type: 'number', section: 'Paramètres' },
      { id: 'revenu_retraite', label: 'Revenu à la retraite ($)', type: 'number', section: 'Paramètres' },
      { id: 'horizon', label: 'Horizon (années)', type: 'number', section: 'Paramètres' },
      { id: 'rendement', label: 'Rendement annuel (%)', type: 'number', section: 'Paramètres', step: '0.1' },
      {
        id: 'reinvestir',
        label: 'Réinvestir le remboursement REER',
        type: 'select',
        section: 'Paramètres',
        options: [
          { value: 'oui', label: 'Oui' },
          { value: 'non', label: 'Non' },
        ],
      },
    ],
    buildPresentation: (r) => ({
      rows: [
        { label: 'REER — valeur nette estimée', value: money(r.reer_final), emphasize: true },
        { label: 'REER — remboursement immédiat', value: money(r.reer_remb) },
        { label: 'REER — impôt au retrait', value: money(r.reer_impot) },
        { label: 'CELI — valeur nette estimée', value: money(r.celi_final), emphasize: true },
        { label: 'Écart', value: money(r.difference) },
        { label: 'Verdict', value: r.verdict_titre || '—' },
      ],
      chart: {
        type: 'stacked-line',
        title: 'Valeur nette finale',
        stacked: false,
        data: [
          { name: 'Investissement', reer: r.reer_cotis || 0, celi: r.celi_cotis || 0 },
          { name: 'Valeur nette', reer: r.reer_final || 0, celi: r.celi_final || 0 },
        ],
        series: [
          { dataKey: 'reer', name: 'REER' },
          { dataKey: 'celi', name: 'CELI' },
        ],
      },
      note: stripEmoji(r.verdict_texte),
    }),
  },

  'calculateur-hypothecaire': {
    defaults: {
      prix: '400000',
      mise: '40000',
      taux: '4.5',
      amortissement: '25',
      frequence: '12',
      schl: 'auto',
    },
    fields: [
      { id: 'prix', label: 'Prix de la propriété ($)', type: 'number', section: 'Prêt' },
      { id: 'mise', label: 'Mise de fonds ($)', type: 'number', section: 'Prêt' },
      { id: 'taux', label: 'Taux d’intérêt (%)', type: 'number', section: 'Prêt', step: '0.05' },
      {
        id: 'amortissement',
        label: 'Amortissement',
        type: 'select',
        section: 'Prêt',
        options: [
          { value: '15', label: '15 ans' },
          { value: '20', label: '20 ans' },
          { value: '25', label: '25 ans' },
          { value: '30', label: '30 ans' },
        ],
      },
      {
        id: 'frequence',
        label: 'Fréquence de paiement',
        type: 'select',
        section: 'Prêt',
        options: [
          { value: '12', label: 'Mensuel' },
          { value: '24', label: 'Bimensuel' },
          { value: '26', label: 'Aux 2 semaines' },
          { value: '52', label: 'Hebdomadaire' },
        ],
      },
      {
        id: 'schl',
        label: 'Assurance SCHL',
        type: 'select',
        section: 'Prêt',
        options: [
          { value: 'auto', label: 'Automatique' },
          { value: 'oui', label: 'Inclure' },
          { value: 'non', label: 'Exclure' },
        ],
      },
    ],
    buildPresentation: (r) => ({
      rows: [
        { label: `Paiement (${r.periode})`, value: money(r.paiement), emphasize: true },
        { label: 'Montant du prêt', value: money(r.montant_pret) },
        { label: 'Prime SCHL', value: money(r.prime_schl) },
        { label: 'Mise de fonds', value: r.mise_pct },
        { label: 'Total des intérêts', value: money(r.total_interets) },
        { label: 'Coût total', value: money(r.cout_total) },
      ],
      chart: {
        type: 'stacked-line',
        title: 'Capital et intérêts (5 premières années)',
        data: (r.tableau_amort || []).map((row) => ({
          name: `An ${row.annee}`,
          capital: Math.round(row.capital),
          interet: Math.round(row.interet),
        })),
        series: [
          { dataKey: 'capital', name: 'Capital remboursé' },
          { dataKey: 'interet', name: 'Intérêts' },
        ],
      },
      note: stripEmoji(r.conseil),
    }),
  },

  'valeur-nette': {
    defaults: {
      cheque: '2000',
      epargne: '5000',
      celi: '15000',
      reer: '40000',
      reee: '8000',
      placements: '10000',
      regime_retraite: '0',
      residence: '350000',
      locatif: '0',
      chalet: '0',
      vehicules: '15000',
      entreprise: '0',
      autres_actifs: '5000',
      hypo_res: '220000',
      hypo_loc: '0',
      marge_hypo: '0',
      pret_auto: '8000',
      pret_etudiant: '0',
      marge_credit: '2000',
      cartes: '1500',
      autres_dettes: '0',
    },
    fields: [
      { id: 'cheque', label: 'Compte chèque ($)', type: 'number', section: 'Liquidités' },
      { id: 'epargne', label: 'Compte épargne ($)', type: 'number', section: 'Liquidités' },
      { id: 'celi', label: 'CELI ($)', type: 'number', section: 'Liquidités' },
      { id: 'reer', label: 'REER ($)', type: 'number', section: 'Placements' },
      { id: 'reee', label: 'REEE ($)', type: 'number', section: 'Placements' },
      { id: 'placements', label: 'Placements non enregistrés ($)', type: 'number', section: 'Placements' },
      { id: 'regime_retraite', label: 'Régime de retraite ($)', type: 'number', section: 'Placements' },
      { id: 'residence', label: 'Résidence principale ($)', type: 'number', section: 'Immobilier' },
      { id: 'locatif', label: 'Immeuble locatif ($)', type: 'number', section: 'Immobilier' },
      { id: 'chalet', label: 'Chalet ($)', type: 'number', section: 'Immobilier' },
      { id: 'vehicules', label: 'Véhicules ($)', type: 'number', section: 'Autres actifs' },
      { id: 'entreprise', label: 'Entreprise ($)', type: 'number', section: 'Autres actifs' },
      { id: 'autres_actifs', label: 'Autres actifs ($)', type: 'number', section: 'Autres actifs' },
      { id: 'hypo_res', label: 'Hypothèque résidence ($)', type: 'number', section: 'Passifs' },
      { id: 'hypo_loc', label: 'Hypothèque locatif ($)', type: 'number', section: 'Passifs' },
      { id: 'marge_hypo', label: 'Marge hypothécaire ($)', type: 'number', section: 'Passifs' },
      { id: 'pret_auto', label: 'Prêt auto ($)', type: 'number', section: 'Passifs' },
      { id: 'pret_etudiant', label: 'Prêt étudiant ($)', type: 'number', section: 'Passifs' },
      { id: 'marge_credit', label: 'Marge de crédit ($)', type: 'number', section: 'Passifs' },
      { id: 'cartes', label: 'Cartes de crédit ($)', type: 'number', section: 'Passifs' },
      { id: 'autres_dettes', label: 'Autres dettes ($)', type: 'number', section: 'Passifs' },
    ],
    buildPresentation: (r) => ({
      rows: [
        { label: 'Total actifs', value: money(r.total_actifs) },
        { label: 'Total passifs', value: money(r.total_passifs) },
        { label: 'Valeur nette', value: money(r.valeur_nette), emphasize: true },
        { label: 'Ratio d’endettement', value: `${r.r_ratio} %` },
        { label: 'Liquidités', value: money(r.total_liquidites) },
        { label: 'Placements', value: money(r.total_placements) },
        { label: 'Immobilier', value: money(r.total_immobilier) },
      ],
      chart: {
        type: 'stacked-line',
        title: 'Répartition du patrimoine',
        data: [
          {
            name: 'Actifs',
            liquidites: r.total_liquidites || 0,
            placements: r.total_placements || 0,
            immobilier: r.total_immobilier || 0,
            autres: r.total_autres_actifs || 0,
            passifs: 0,
          },
          {
            name: 'Passifs',
            liquidites: 0,
            placements: 0,
            immobilier: 0,
            autres: 0,
            passifs: r.total_passifs || 0,
          },
        ],
        series: [
          { dataKey: 'liquidites', name: 'Liquidités' },
          { dataKey: 'placements', name: 'Placements' },
          { dataKey: 'immobilier', name: 'Immobilier' },
          { dataKey: 'autres', name: 'Autres actifs' },
          { dataKey: 'passifs', name: 'Passifs' },
        ],
      },
      note: stripEmoji(r.conseil),
    }),
  },

  'comparateur-rendements': {
    defaults: {
      profil: 'equilibre',
      rendement_perso: String(getBanqueAvgForProfil('equilibre')),
      capital: '50000',
      horizon: '5',
      versement: '0',
    },
    /** Le champ rendement suit toujours le profil (moyenne banques), sauf saisie manuelle après. */
    syncValues: (values, id, value) => {
      const next = { ...values, [id]: value };
      if (id === 'profil') {
        next.rendement_perso = String(getBanqueAvgForProfil(value));
      }
      return next;
    },
    fields: [
      {
        id: 'profil',
        label: 'Profil de risque',
        type: 'select',
        section: 'Comparaison',
        fullWidth: true,
        options: Object.keys(PROFIL_RISQUE_LABELS).map((key) => ({
          value: key,
          label: `${PROFIL_RISQUE_LABELS[key]} — iA ${formatPctFr(getIaPctForProfil(key))} %`,
        })),
        hint: (values) => {
          const profil = values.profil || 'equilibre';
          return `Portefeuille modèle iA : ${formatPctFr(getIaPctForProfil(profil))} % net sur 5 ans. La moyenne banques se met à jour dans le champ ci-dessous.`;
        },
      },
      {
        id: 'rendement_perso',
        label: 'Rendement 5 ans — banques / vous (%)',
        type: 'number',
        section: 'Comparaison',
        step: '0.1',
        fullWidth: true,
        hint: (values) => {
          const profil = values.profil || 'equilibre';
          const banque = formatPctFr(getBanqueAvgForProfil(profil));
          return `Prérempli avec la moyenne illustrative des banques pour ce profil (~${banque} %). Modifiez-le pour utiliser votre rendement personnel.`;
        },
      },
      { id: 'capital', label: 'Capital investi ($)', type: 'number', section: 'Projection' },
      {
        id: 'horizon',
        label: 'Horizon',
        type: 'select',
        section: 'Projection',
        options: [
          { value: '5', label: '5 ans' },
          { value: '10', label: '10 ans' },
          { value: '15', label: '15 ans' },
          { value: '20', label: '20 ans' },
        ],
      },
      { id: 'versement', label: 'Versement annuel ($)', type: 'number', section: 'Projection' },
    ],
    buildPresentation: (r) => ({
      rows: [
        { label: 'Profil', value: r.r_profil },
        { label: 'Moyenne banques (profil)', value: pct(r.banque_avg) },
        { label: 'Rendement utilisé', value: pct(r.utilise_pct) },
        { label: 'Modèle iA (5 ans net)', value: pct(r.ia_pct), emphasize: true },
        { label: 'Écart de rendement', value: `${Number(r.ecart_pts).toFixed(1).replace('.', ',')} pts` },
        { label: 'Valeur scénario banque / vous', value: money(r.valeur_banque) },
        { label: 'Valeur scénario iA', value: money(r.valeur_ia), emphasize: true },
        { label: 'Écart estimé', value: money(r.ecart_dollars) },
      ],
      chart: {
        type: 'stacked-line',
        title: 'Projection comparative',
        stacked: false,
        data: [
          {
            name: 'Départ',
            banque: r.capital || 0,
            ia: r.capital || 0,
          },
          {
            name: `${r.horizon || 5} ans`,
            banque: r.valeur_banque || 0,
            ia: r.valeur_ia || 0,
          },
        ],
        series: [
          { dataKey: 'banque', name: 'Banque / vous' },
          { dataKey: 'ia', name: 'Modèle iA' },
        ],
      },
      note: stripEmoji(r.r_resume),
    }),
  },
};
